### ISSUE TITLE
Integración Marketplace

### ISSUE THREAD

**Issue by agustinzamar** [mercadopago/checkout-payment-sample#20]
Estoy armando una integracion tipo marketplace usando checkout pro

1. En el frontend inicializo el componente con la Public Key del marketplace `initMercadoPago(import.meta.env.VITE_MERCADOPAGO_PUBLIC_KEY);`
2. En el backend creo la preferencia utilizando el Access Token del vendedor 

```
public function setAccessToken(?Event $event): void
    {
        $mpToken = $event->mpToken()->first();

        if (!$mpToken) {
            abort(500, 'Undefined Mercado Pago Token for event');
        }

        SDK::setAccessToken($mpToken->access_token);
    }

    public function savePreference(Collection $items, int $externalReference): MercadoPagoPreference
    {
        $preference = new MercadoPagoPreference();

        $preference->notification_url = url('/api/mercadopago/notifications');
        $preference->external_reference = $externalReference;
        $preference->payer = $this->createPayer();

        $preference->binary_mode = true;
        $preference->marketplace_fee = $items->sum(fn($item) => $item->quantity * $item->unit_price) * 0.1;

        $preference->items = $items->toArray();

        $preference->save();

        return $preference;
    }
```

Al hacer click sobre el boton de pago obtengo el siguiente error 

```
{
    "code": "unauthorized",
    "message": "Unable to acquire requested preference from the resource."
}
```

**Comment by tomasmenniti** [comment]
hola agustin y perdon por molestar: pudiste resolver este error? llevo semanas y no logro entender el por que. Al igual que vos, inicializo el comopnente con la public key de mi cuenta, y en el backend tambien creo la preferencia con el access token del vendedor

**Comment by agustinzamar** [comment]
Hola como estas? No recuerdo como lo solucione. Estás usando usuarios de prueba para todo? Deberias tener al menos 3 usuarios de prueba creados en tu cuenta productiva de meli.

Con uno de los usuarios creas una nueva integración y usas las credenciales de producción de esa integración. (Este seria el marketplace)

Y los otros 2 usuarios serian comprador y vendedor respectivamente.

Cuando haces el proceso de OAuth para que el vendedor se vincule a tu sistema, no pongas el parámetro test=true como dice la documentación.

Avisame si con algo de eso se soluciona!

**Comment by tomasmenniti** [comment]
Hola genio y muchas gracias por responder. Ya mismo me pongo a probar eso,
pero me queda una duda: cuando pase a producción como reemplazo los datos
de la app de la cuenta de prueba?

**Comment by agustinzamar** [comment]
Todo lo que sean datos secretos de MP como el access token e incluso la public key deberias tenerlo en un archivo .env. Si nunca usaste te recomiendo mucho que veas algun tutorial según el lenguaje y framework que estes usando.

No hardcodees esas credenciales en el código y no las subas a tu repositorio.

Luego en producción vas a tener que crear ese archivo .env nuevamente y le pones las credenciales de producción de tu usuario productivo de MP.

Te recomiendo que veas [este video](https://youtu.be/BUHUW7tAr_Y?si=Qz5qiIpfIdmlRGX7)aunque no estes usando next
